name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github event name : ${{ github.event_name }}"
          echo "Github ref : ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "List files :"
          tree

  
